In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cpu


In [3]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

In [4]:
a = torch.empty(2,3)

In [5]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
type(a)

torch.Tensor

In [7]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(3,4)

tensor([[0.8288, 0.7899, 0.7800, 0.8160],
        [0.8974, 0.7732, 0.9998, 0.4527],
        [0.1629, 0.1569, 0.0052, 0.1169]])

In [11]:
torch.rand(3,4)

tensor([[0.0790, 0.8151, 0.4018, 0.9905],
        [0.9803, 0.8054, 0.1918, 0.1872],
        [0.5407, 0.5376, 0.2853, 0.5438]])

In [12]:
torch.rand(3,4)

tensor([[0.6230, 0.5275, 0.3374, 0.7879],
        [0.2768, 0.6147, 0.6673, 0.2309],
        [0.3710, 0.5250, 0.6293, 0.8697]])

In [13]:
torch.manual_seed(10)
torch.rand(3,4)


tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [14]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [15]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [22]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [23]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [25]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [26]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [31]:
torch.linspace(0,1,30)

tensor([0.0000, 0.0345, 0.0690, 0.1034, 0.1379, 0.1724, 0.2069, 0.2414, 0.2759,
        0.3103, 0.3448, 0.3793, 0.4138, 0.4483, 0.4828, 0.5172, 0.5517, 0.5862,
        0.6207, 0.6552, 0.6897, 0.7241, 0.7586, 0.7931, 0.8276, 0.8621, 0.8966,
        0.9310, 0.9655, 1.0000])

In [32]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [33]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [34]:
x = torch.tensor([[1,2,3],[3,4,5]])

In [35]:
x.shape

torch.Size([2, 3])

In [36]:
torch.empty_like(x)

tensor([[8027140907415206688, 7018332503360695925, 7146421190002045804],
        [                 65,           150197328,     136761237523728]])

In [37]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [39]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [40]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [41]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [42]:
x-2

tensor([[-1,  0,  1],
        [ 1,  2,  3]])

In [43]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [44]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [45]:
c = torch.tensor([1, -2, 3, -4])

In [46]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [47]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [48]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [49]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [50]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [52]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [58]:
e=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)

In [60]:
e

tensor([[8., 7., 9., 8.],
        [5., 1., 2., 5.],
        [7., 8., 1., 2.]])

In [59]:
torch.sum(e)

tensor(63.)

In [61]:
torch.sum(e, dim=0)

tensor([20., 16., 12., 15.])

In [62]:
torch.sum(e, dim=1)

tensor([32., 13., 18.])

In [63]:
torch.mean(e, dim=1)

tensor([8.0000, 3.2500, 4.5000])

In [64]:
torch.mean(e)

tensor(5.2500)

In [65]:
torch.min(e)

tensor(1.)

In [66]:
torch.max(e)

tensor(9.)

argmax it is giving me index of highest value in matrix

In [67]:
torch.argmax(e)

tensor(2)

argmin it is giving me a index of minimum value in matrix

In [68]:
torch.argmin(e)

tensor(5)

In [69]:
e

tensor([[8., 7., 9., 8.],
        [5., 1., 2., 5.],
        [7., 8., 1., 2.]])

In [70]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [71]:
f

tensor([[1, 5, 3],
        [4, 0, 2]])

In [72]:
g

tensor([[5, 2],
        [9, 9],
        [1, 3]])

In [ ]:
2*3, 3*2 = 2*2

In [73]:
torch.matmul(f,g)

tensor([[53, 56],
        [22, 14]])

In [74]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [75]:
vector1

tensor([1, 2])

In [76]:
vector2

tensor([3, 4])

In [77]:
torch.dot(vector1,vector2)

tensor(11)

In [78]:
f

tensor([[1, 5, 3],
        [4, 0, 2]])

In [80]:
torch.transpose(f,0,1)

tensor([[1, 4],
        [5, 0],
        [3, 2]])

In [82]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [83]:
h

tensor([[6., 1., 9.],
        [9., 0., 9.],
        [2., 5., 9.]])

In [84]:
torch.inverse(h)

tensor([[-0.6250,  0.5000,  0.1250],
        [-0.8750,  0.5000,  0.3750],
        [ 0.6250, -0.3889, -0.1250]])

In [85]:
torch.log(h)

tensor([[1.7918, 0.0000, 2.1972],
        [2.1972,   -inf, 2.1972],
        [0.6931, 1.6094, 2.1972]])

In [86]:
torch.exp(h)

tensor([[4.0343e+02, 2.7183e+00, 8.1031e+03],
        [8.1031e+03, 1.0000e+00, 8.1031e+03],
        [7.3891e+00, 1.4841e+02, 8.1031e+03]])

In [88]:
torch.softmax(h,0)

tensor([[4.7385e-02, 1.7868e-02, 3.3333e-01],
        [9.5175e-01, 6.5733e-03, 3.3333e-01],
        [8.6788e-04, 9.7556e-01, 3.3333e-01]])

NN module
dataset and dataloader
gredient
training of nn on some data
transformer code

PyTorch makes **differentiation** (computing gradients) easy and efficient by providing the **autograd** package. This allows you to automatically compute the gradients of tensors during backpropagation, which is essential for training machine learning models, particularly in deep learning.

### Concept of autograd

### NN Module of Pytorch

### Dataset and Dataloader

In [52]:
def dy_dx(x):
    return 2*x

In [54]:
dy_dx(4)

8

In [55]:
import torch
x=torch.tensor(3.0,requires_grad=True)

In [56]:
x

tensor(3., requires_grad=True)

In [57]:
y=x**2

In [ ]:
y=2*x

In [58]:
y

tensor(9., grad_fn=<PowBackward0>)

In [59]:
y.backward()

In [60]:
x.grad

tensor(6.)

In [61]:
import math
def dz_dx(x):
    return 2*x*math.cos(x**2)

In [71]:
dz_dx(3)

-5.466781571308061

In [63]:
dz_dz(5)

9.912028118634735

In [64]:
x=torch.tensor(3.0,requires_grad=True)

In [65]:
x

tensor(3., requires_grad=True)

In [66]:
y=x**2
z=torch.sin(y)

In [67]:
y

tensor(9., grad_fn=<PowBackward0>)

In [68]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [69]:
z.backward()

In [70]:
x.grad

tensor(-5.4668)

In [73]:
import torch.nn as nn

In [ ]:
class Model(nn.Module):
    def __init__(self):
        pass
    def forward(self):
        pass