In [1]:
sentences = ["I ate dinner.", 
       "We had a three-course meal.", 
       "Brad came to dinner with us.",
       "He loves fish tacos.",
       "In the end, we all felt like we ate too much.",
       "We all agreed; it was a magnificent evening."]

In [ ]:
1. setence transformer
2. langchain hugging
3. transformer

In [ ]:
!pip install sentence-transformer

In [3]:
from sentence_transformers import  SentenceTransformer

In [4]:
model = SentenceTransformer('all-mpnet-base-v2')

In [5]:
sentences[0]

'I ate dinner.'

In [6]:
model.encode(sentences[0])

array([-1.58597678e-02,  4.59826551e-02, -1.46349585e-02, -4.85908687e-02,
       -3.60319996e-03,  3.17664109e-02, -3.27771641e-02,  2.11895313e-02,
        1.07366042e-02,  2.50182096e-02,  1.58237889e-02,  1.24069359e-02,
        1.62089840e-02, -1.30434325e-02,  4.58446629e-02,  4.40269858e-02,
        4.57802415e-02, -4.32259543e-03,  1.87806357e-02,  5.22195548e-03,
       -1.86415315e-02, -7.11804302e-03,  3.01359687e-02,  1.70695819e-02,
       -1.53764402e-02,  3.34172398e-02, -6.55884482e-03,  1.58591792e-02,
        1.37038892e-02, -2.02767160e-02,  3.26631889e-02,  5.48361661e-03,
       -3.53351422e-02, -1.06665209e-01,  1.85711565e-06,  3.66638750e-02,
       -1.71336550e-02,  3.34468447e-02, -6.43022060e-02,  6.90796226e-02,
        2.50845030e-02,  2.89430898e-02, -8.98415409e-03, -1.84546430e-02,
        2.81152073e-02, -2.34797206e-02,  1.21612307e-02,  6.25151247e-02,
       -8.58704001e-02, -1.84621708e-03,  7.95865990e-03, -8.42522830e-02,
       -2.26104409e-02,  

In [7]:
model.encode(sentences[0]).shape

(768,)

In [ ]:
!pip install langchain
!pip install langchain-community

In [8]:
from langchain.embeddings import HuggingFaceEmbeddings

In [9]:
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"

In [10]:
model_kwargs = {"device": "cpu"}
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name,model_kwargs=model_kwargs)

C:\Users\sunny\AppData\Local\Temp\ipykernel_69960\2861529945.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name,model_kwargs=model_kwargs)


In [11]:
embedding_vector = embeddings.embed_query(sentences[0])

In [12]:
embedding_vector

[-0.01585976779460907,
 0.04598265513777733,
 -0.01463495846837759,
 -0.04859086871147156,
 -0.00360319996252656,
 0.031766410917043686,
 -0.03277716413140297,
 0.021189531311392784,
 0.01073660422116518,
 0.02501820959150791,
 0.015823788940906525,
 0.012406935915350914,
 0.016208983957767487,
 -0.013043432496488094,
 0.0458446629345417,
 0.04402698576450348,
 0.0457802414894104,
 -0.004322595428675413,
 0.01878063566982746,
 0.005221955478191376,
 -0.018641531467437744,
 -0.007118043024092913,
 0.030135968700051308,
 0.017069581896066666,
 -0.01537644024938345,
 0.0334172397851944,
 -0.006558844819664955,
 0.015859179198741913,
 0.013703889213502407,
 -0.020276715978980064,
 0.03266318887472153,
 0.005483616609126329,
 -0.03533514216542244,
 -0.10666520893573761,
 1.857115648817853e-06,
 0.03666387498378754,
 -0.01713365502655506,
 0.033446844667196274,
 -0.06430220603942871,
 0.06907962262630463,
 0.02508450299501419,
 0.02894308976829052,
 -0.008984154090285301,
 -0.018454642966389

In [13]:
len(embedding_vector)

768

### one more approach with tranformer huggingface libary

In [14]:
import torch
from transformers import BertTokenizer, BertModel
import random

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
random_seed=42
random.seed(random_seed)
torch.manual_seed(random_seed)

In [15]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

In [16]:
model=BertModel.from_pretrained("bert-base-uncased")

In [17]:
text="follow sunny for genai learning"

In [18]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [21]:
input_ids=encoding["input_ids"]

In [22]:
attention_mask=encoding["attention_mask"]

In [23]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [24]:
word_embeddings

tensor([[[-0.0046, -0.1060, -0.0177,  ...,  0.0474,  0.0697,  0.2605],
         [ 0.8739, -0.1599,  0.5948,  ...,  0.4223,  0.2269, -0.1508],
         [ 0.0209, -0.3746, -0.2735,  ...,  0.3497,  0.0062, -0.4563],
         ...,
         [-0.2692, -0.4198, -0.1005,  ..., -0.0563, -0.2520, -0.6442],
         [-0.4552, -0.7338, -0.2614,  ...,  0.8366,  0.2496, -0.1972],
         [ 0.8920,  0.1769, -0.2345,  ...,  0.3265, -0.7962, -0.2090]]])

In [25]:
word_embeddings.shape

torch.Size([1, 8, 768])

In [26]:
input_ids[0]

tensor([  101,  3582, 11559,  2005,  8991,  4886,  4083,   102])

In [27]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [28]:
decode

'follow sunny for genai learning'

### these above entire techniques based on the trasnformer model

## which we gonna use in further classes (for RAG, Finetuning etc)